task: comfact

save_dir: data/saved_models/qagnn-comfact
checkpoint: true

seed: 0

data:
  num_relation: 2

  train_path: data/processed-comfact/complete-2/movie/train.pk
  dev_path: data/processed-comfact/complete-2/movie/dev.pk
  test_path: data/processed-comfact/complete-2/movie/test.pk

  batch_size: 8
  accumulate_grad_batches: 1

  node_embeddings_path: data/embeddings/augmented_graph_embeddings.npy

  use_cache: true

model:
  encoder:
    name: roberta-base
    layer: -1
  decoder:
    name: gat
    num_layers: 2
    att_head_num: 2
    gnn_dim: 100
    fc_dim: 100
    fc_layer_num: 0

    ent_emb: tzw
    freeze_ent_emb: true
    max_node_num: 500
    simple: false
    subsample: 1.0
    init_range: 0.02

    dropouti: 0.1
    dropoutg: 0.1
    dropoutf: 0.1

training:
  num_epochs: 50
  max_epochs_before_stop: 10
  max_seq_len: 500
  log_interval: 10

  finetune_only_last_layer: false
  unfreeze_epoch: 10000
  refreeze_epoch: 10000
  freeze_ent_emb: true

  fp16: false

  loss: binary_cross_entropy
  max_grad_norm: 1.0

optimization:
  optim: adamw
  lr_schedule: warmup_linear

  decoder_lr: 1e-3
  encoder_lr: 1e-5
  warmup_steps: 200
  weight_decay: 1e-2

  drop_partial_batch: false
  fill_partial_batch: false
